"""added one column

Revision ID: 0e0ea10496ab
Revises: ed0469b32b52
Create Date: 2022-09-07 02:30:16.437519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0ea10496ab'
down_revision = 'ed0469b32b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('tool_type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'tool_type')
    # ### end Alembic commands ###
