"""altered tables

Revision ID: 24ac616b760a
Revises: c8a8af19ff84
Create Date: 2022-09-04 10:42:34.916484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24ac616b760a'
down_revision = 'c8a8af19ff84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tools_designation_id_fkey', 'tools', type_='foreignkey')
    op.drop_column('tools', 'designation_id')
    op.add_column('user', sa.Column('designation_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('user_designations_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'designations', ['designation_id'], ['id'])
    op.drop_column('user', 'lockout_end')
    op.drop_column('user', 'last_login_date')
    op.drop_column('user', 'lockout_enabled')
    op.drop_column('user', 'access_failed_count')
    op.drop_column('user', 'designations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('designations', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('access_failed_count', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lockout_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_login_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('lockout_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_designations_fkey', 'user', 'designations', ['designations'], ['id'])
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'designation_id')
    op.add_column('tools', sa.Column('designation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tools_designation_id_fkey', 'tools', 'projects', ['designation_id'], ['id'])
    # ### end Alembic commands ###
