"""3rd version

Revision ID: e817869fdb4b
Revises: 0e0ea10496ab
Create Date: 2022-09-12 19:37:09.204839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e817869fdb4b'
down_revision = '0e0ea10496ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('designationtools_project_id_fkey', 'designationtools', type_='foreignkey')
    op.drop_constraint('designationtools_tool_id_fkey', 'designationtools', type_='foreignkey')
    op.drop_constraint('designationtools_designation_id_fkey', 'designationtools', type_='foreignkey')
    op.create_foreign_key(None, 'designationtools', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'designationtools', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'designationtools', 'designations', ['designation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'designationtools', type_='foreignkey')
    op.drop_constraint(None, 'designationtools', type_='foreignkey')
    op.drop_constraint(None, 'designationtools', type_='foreignkey')
    op.create_foreign_key('designationtools_designation_id_fkey', 'designationtools', 'designations', ['designation_id'], ['id'])
    op.create_foreign_key('designationtools_tool_id_fkey', 'designationtools', 'tools', ['tool_id'], ['id'])
    op.create_foreign_key('designationtools_project_id_fkey', 'designationtools', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
