"""cascade demo

Revision ID: ed0469b32b52
Revises: 24ac616b760a
Create Date: 2022-09-07 01:50:36.735445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0469b32b52'
down_revision = '24ac616b760a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ktlinks_project_id_fkey', 'ktlinks', type_='foreignkey')
    op.create_foreign_key(None, 'ktlinks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ktlinks', type_='foreignkey')
    op.create_foreign_key('ktlinks_project_id_fkey', 'ktlinks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
